# Generated by Django 4.0.3 on 2022-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='data',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
