# Generated by Django 4.0.3 on 2022-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_city_lat_city_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
