# Generated by Django 4.0.3 on 2022-05-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weather_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='image',
        ),
    ]
